spring:
  datasource:
    schema: schema.sql

# MyBatis
mybatis:
  type-aliases-package: com.workout.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      workout: trace